### ISSUE TITLE
BUG: Normalize input to /sys/fs/selinux/enforce

### ISSUE THREAD

**Issue by stephensmalley** [SELinuxProject/selinux-kernel#10]
At present, one can write any signed integer value to /sys/fs/selinux/enforce and it will be stored, e.g. echo -1 > /sys/fs/selinux/enforce or echo 1999 > /sys/fs/selinux/enforce.  This makes no real difference to the kernel, since it only ever cares if it is zero or non-zero, but some userspace code compares it with 1 to decide if SELinux is enforcing, and this could confuse it.  Only a process that is already root and is allowed the setenforce permission in SELinux policy can write to /sys/fs/selinux/enforce, so this is not considered to be a security issue, but it should be fixed.

**Comment by pcmoore** [comment]
Merged via ea49d10eee5a220b717dbf2ee429c9e3d59c978c.
