### ISSUE TITLE
RFE: add LSM/SELinux access controls for cgroups

### ISSUE THREAD

**Issue by pcmoore** [SELinuxProject/selinux-kernel#23]
Look into adding access controls for control groups.

* https://en.wikipedia.org/wiki/Cgroups

**Comment by stephensmalley** [comment]
Related: cgroup_procs_write_permission() performs a UID check between the current task and the target task.  There should be a security hook there and a corresponding SELinux check.

**Comment by stephensmalley** [comment]
Is this OBE by the fact that kernfs now fully supports file security labeling and inheritance, and cgroup2 performs a general inode_permission() check rather than a hardcoded uid check in its cgroup_procs_write_permission() function

**Comment by pcmoore** [comment]
Probably, or at least I think we can consider the basic requirement satisfied until we get some more specific requirements.  I'll close this out for now.
