### ISSUE TITLE
RFE: add LSM/SELinux support for InfiniBand RDMA

### ISSUE THREAD

**Issue by pcmoore** [SELinuxProject/selinux-kernel#25]
See the latest submission upstream:

* https://marc.info/?l=selinux&m=147991097107455&w=2

One major concern is if we can support the different RDMA backends with a single set of LSM hooks; earlier discussion indicates that may not be possible.

**Comment by stephensmalley** [comment]
Resolved by commits:
883c71feaf2e810e0331cf780c738cbb09e93b58
d291f1a6523292d916fe1659c67f6db061fbd1b5
8f408ab64be6319cb7736cbc6982838dcc362306
47a2b338fe63200d716d2e24131cdb49f17c77da
a806f7a1616f29b80749d708115a643c1f4ba056
3a976fa6767f3edebbf43839b686efaf71b8dee1
cfc4d882d41780d93471066d57d4630995427b29
ab861dfca1652aa09b26b7aa2899feb29b33dfd9
409dcf31538ae6ae96b3a0a1d3211e668bfefe8b
