### ISSUE TITLE
RFE: always return a value from the netport/netnode/netif caches

### ISSUE THREAD

**Issue by stephensmalley** [SELinuxProject/selinux-kernel#3]
Currently under memory pressure the netport/netnode/netif caches can fail to return a SID to the caller, thereby causing an operation to fail.  However, the cache can always return the value obtained from the security server, even if it cannot allocate a cache node to save it for future lookups (just as the AVC does).  Fix the caches to do so.

**Comment by pcmoore** [comment]
An uncompiled and untested initial draft:

* https://github.com/pcmoore/misc-linux_kernel/tree/working-gh3

**Comment by pcmoore** [comment]
Currently in selinux/next via 9b80c36353ed4cce324af21244a65984db21991b.
