### ISSUE TITLE
BUG: policy reload can trigger transient userspace failures with ENOMEM errors

### ISSUE THREAD

**Issue by stephensmalley** [SELinuxProject/selinux-kernel#38]
As reported by Li Kun on selinux list, a policy reload can cause a transient failure in allocating a new context/SID, thereby breaking userspace, e.g. docker calls setexeccon(3) and this interleaves with a policy reload such that it fails with ENOMEM.  This is due to sidtab_context_to_sid() returning ENOMEM when the sidtab has been shutdown.  During policy reload, we shut down the sidtab to prevent creating allocating any new SIDs/contexts before we copy and remap all of the existing sidtab entries for the new policy. A short term fix for this would be to return EINTR in this case instead, which is already handled by libselinux and will cause the operation to be retried, allowing it to proceed once the policy switch has completed. A longer term fix is to rework the way policy reload occurs to avoid any need to shut down the sidtab.

**Comment by opoplawski** [comment]
Possible downstream report - https://bugzilla.redhat.com/show_bug.cgi?id=1335986

**Comment by stephensmalley** [comment]
Bug isn't open (at least not to me), so that isn't very helpful.

**Comment by pcmoore** [comment]
It's not open to me either.

It's also worth noting that downstream bugs don't always mean there is a problem upstream, especially when the downstream kernel has diverged significant from upstream.

**Comment by opoplawski** [comment]
Ah, sorry.  If you have RedHat bugzilla logins I probably could add you to the cc list if desired.  I can't make it public though.

**Comment by pcmoore** [comment]
I have a Red Hat bugzilla account for Fedora work, but this is something you should probably bring up with @WOnder93 if you haven't already.

**Comment by WOnder93** [comment]
For the record, here is my initial take on fixing this problem:
https://lore.kernel.org/selinux/20181031122718.18735-1-omosnace@redhat.com/

Today, I posted another patchset with a cleaner (but more complex) solution that also improves performance of some sidtab operations as a bonus:
https://lore.kernel.org/selinux/20181113135255.26045-1-omosnace@redhat.com/

**Comment by WOnder93** [comment]
@boazsapir: Yes, the symptoms definitely check out, but for Red Hat specific questions please use official RH channels (there is a RHEL-7 bugzilla open [1] or you might want to open a customer case). I can't give you any official commitment, although I can say that work is ongoing to backport the fix to the next minor version of RHEL-7, so cross your fingers ;)

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1335986

**Comment by pcmoore** [comment]
Since I think we've fixed this upstream - @WOnder93? - I'm going to close this issue, feel free to reopen if needed.
