### ISSUE TITLE
RFE: add controls over userfaultfd

### ISSUE THREAD

**Issue by pcmoore** [SELinuxProject/selinux-kernel#48]
From @stephensmalley on the [SELinux mailing list](https://lore.kernel.org/selinux/672ca771-12f4-b6c2-c05c-446860c05a0d@tycho.nsa.gov/):

>  Commit cefdca0a86be517bc390fc4541e3674b8e7803b0 introduced a vm.unprivileged_userfaultfd sysctl that can be set to 0 to restrict use of userfaultfd to processes with CAP_SYS_PTRACE (hence SELinux sys_ptrace), but that only restricts the userfaultfd() system call itself, not subsequent operations on the returned file.

This likely depends on issue #47.

**Comment by stephensmalley** [comment]
Ran across this:
https://lore.kernel.org/lkml/20191012191602.45649-1-dancol@google.com/
Looks like they were told to cc lsm on future versions and it also spawned this related patch:
https://lore.kernel.org/lkml/1572967777-8812-1-git-send-email-rppt@linux.ibm.com/

**Comment by stephensmalley** [comment]
FTR, I belatedly replied to the above cited thread and asked them to cc selinux list in the future as well.

**Comment by stephensmalley** [comment]
Two possible approaches for addressing this issue have been posted to selinux list in
https://lore.kernel.org/selinux/20200211225547.235083-1-dancol@google.com/ and
https://lore.kernel.org/selinux/20200213194157.5877-1-sds@tycho.nsa.gov/

**Comment by stephensmalley** [comment]
Applied to the linux-security tree as per https://lore.kernel.org/selinux/alpine.LRH.2.21.2006041354381.1812@namei.org/

**Comment by stephensmalley** [comment]
Fixed by b537900f1598b67bcb8acac20da73c6e26ebbf99
