### ISSUE TITLE
RFE: Add SELinux SCTP support

### ISSUE THREAD

**Issue by stephensmalley** [SELinuxProject/selinux-kernel#5]
There was a patch set that did this back in 2015; I don't really know why it didn't progress to merging.

**Comment by stephensmalley** [comment]
RFC patchset from Richard Haines
   * https://marc.info/?l=linux-sctp&m=142219887901738&w=2

**Comment by pcmoore** [comment]
An update from Richard Haines:

* https://marc.info/?l=selinux&m=147948805506276&w=2

**Comment by stephensmalley** [comment]
Fixed by d452930fd3b9031e59abfeddb2fa383f1403d61a, will be in 4.17, requires enabling extended_socket_class policy capability in policy to leverage.
