### ISSUE TITLE
BUG: selinux policy reload is not atomic wrt selinuxfs

### ISSUE THREAD

**Issue by stephensmalley** [SELinuxProject/selinux-kernel#52]
Presently SELinux policy reload is not atomic wrt updating selinuxfs, so a failure while updating selinuxfs (e.g. while creating the new booleans or class subdirectories) will leave the system in an inconsistent state.  Fixing this requires refactoring policy load as per https://lore.kernel.org/selinux/20181002155810.GP32577@ZenIV.linux.org.uk/

**Comment by pcmoore** [comment]
Related to #51.

**Comment by pcmoore** [comment]
Adding @dburgener.

**Comment by stephensmalley** [comment]
Partly fixed via 02a52c5c8c3b8cbad0f12009cde9f36dbefb6972; an error while updating selinuxfs will now leave the system running with the old policy.  selinuxfs itself may still be in an inconsistent state; this will be addressed via #52.
