### ISSUE TITLE
RFE: allow self in typetransition for anon_inode transitions

### ISSUE THREAD

**Issue by doverride** [SELinuxProject/selinux-kernel#59]
anon_inode transitions happen on self/create but the typetransition statement does not accept self.

**Comment by pcmoore** [comment]
Hi @doveride,

I'm going to close this out as I think this is a policy language and/or compiler issue as the kernel generally doesn't have the concept of "self" with respect to access controls decisions.  FWIW, the kernel is definitely using the same value for the subject and object in the `anon_inode` transition, see the code snippet below (taken from `selinux_inode_init_security_anon(...)`):
```c
                isec->sclass = SECCLASS_ANON_INODE;
                rc = security_transition_sid(
                        &selinux_state, tsec->sid, tsec->sid,
                        isec->sclass, name, &isec->sid);
                if (rc)
                        return rc;
```

**Comment by pcmoore** [comment]
Thanks @WOnder93, is it worth creating an issue in the GH userspace repo to track this?
