### ISSUE TITLE
SELinux Kernel Subsystem

### ISSUE THREAD

**Issue by Mikksrund** [SELinuxProject/selinux-kernel#63]
https://github.com/SELinuxProject/selinux-kernel

https://git.kernel.org/pub/scm/linux/kernel/git/pcmoore/selinux.git https://github.com/SELinuxProject/selinux-kernel

Documentation/admin-guide/README.rst

**Comment by pcmoore** [comment]
Hi @Mikksrund, I'm going to close this issue as it appears to be a collection of links to SELinux source repos and documentation.  If you have a question, bug report, or other request please feel free to reopen this issue with some additional information so we can help you.
